import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Scanner;

public class Custom89 {
    public static void main (String [] args)throws NoSuchAlgorithmException{

        Custom89read g = new Custom89read();
        g.Timer();
        g.adminPassword();

        int i = 100;
        System.out.println(i);
        Scanner scanner = new Scanner(System.in);
        System.out.println("Enter Email");
        String input = scanner.nextLine();
        if (input.equalsIgnoreCase("CoBossAdmin@ShinHotel.com")) {
            System.out.println("Enter Password");
            String password = scanner.nextLine();
            String cuc = getMd5(password);
          //  System.out.println("Your HashCode Generated by MD5 is: " + getMd5(password));
            if (cuc.equals("cc8d4ed32c637f5c78373a729063f863")) {//SHINCOCHAN@COBOSS12
                g.Welcome();
                g.openFile();
                g.readFile();
                g.closeFile();
                g.idGenerator();
            }else{
                System.out.println("Wrong password");
            }
        }else{
            System.out.println("Wrong email");
        }
    }



    public static String getMd5(String input)
    {
        try {

            // Static getInstance method is called with hashing MD5
            MessageDigest md = MessageDigest.getInstance("MD5");

            // digest() method is called to calculate message digest
            //  of an input digest() return array of byte
            byte[] messageDigest = md.digest(input.getBytes());

            // Convert byte array into signum representation
            BigInteger no = new BigInteger(1, messageDigest);

            // Convert message digest into hex value
            String hashtext = no.toString(16);
            while (hashtext.length() < 32) {
                hashtext = "0" + hashtext;
            }
            return hashtext;
        }


        // For specifying wrong message digest algorithms
        catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
    }
}

